[tool.uv]
exclude-newer = "7 days"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["gha_harden"]

[project]
name = "gha-harden"
version = "0.1.0"
description = "Harden GitHub Action workflows by pinning versions"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Ross MacArthur", email = "ross@macarthur.io" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
    "rich>=15.0.0",
]

[project.scripts]
gha-harden = "gha_harden:main"

[dependency-groups]
dev = [
    "coverage",
    "pytest",
    "ruff",
    "ty",
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
extend-select = [
    "I",       # isort
    "G",       # flake8-logging-format
    "PIE",     # flake8-pie
    "ANN001",  # missing-type-function-argument
    "ANN2",    # missing-return-type
]
unfixable = [
    "F841",   # unused-variable, annoying for development when autofixed
]

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true
